# Application configuration demo file for OpenCourse.
# This file is a template and should be copied to application.yml for local use.

# Spring Boot configuration.
spring:
  # Application Information.
  application:
    name: "OpenCourse"
  # SQL settings.
  sql:
    init:
      mode: "never"
  # Database settings.
  datasource:
    url: "jdbc:mysql://mysql:3306/opencourse_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true"
    username: "opencourse_user"
    password: "12345678"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  # JPA/Hibernate settings.
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        # Character encoding settings.
        connection:
          characterEncoding: "utf8"
          useUnicode: true
    open-in-view: false
  # Email settings.
  mail:
    host: "smtp.163.com"
    port: 465
    username: "Budg3tB33@163.com"
    password: "GYbbMZS3vh2iFEpA"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: "smtp.163.com"
  # File upload settings.
  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "100MB"
      enabled: true
  # Security settings.
  security:
    user:
      name: YOUR_ADMIN_USERNAME       # Change to your admin username
      password: YOUR_ADMIN_PASSWORD   # Change to your admin password

# Server settings.
server:
  port: 8080

# Logging settings.
logging:
  level:
    org.opencourse: "INFO"
    root: "WARN"

# MinIO settings.
minio:
  endpoint: " http://minio:9000"
  access-key: "root"
  secret-key: "12345678"
  bucket-name: "opencourse-resource-files"

# JWT settings.
jwt:
  secret: "ZGY4ZjE2MzMxNDhmNGU4ZThlYjQ5ZGQ3MTk0MzUyOWY4YjA3NGNiZTY5ZjIxMjUzOGI3NmY4ZGRjNTg4ZmVjNzhmOWQ0YWE2YTZjZGY0MzI4YmJmMGQ3YzQ5NTI3NzA3NDA4NGRhOWI5ZmRjM2Y4NDk2YzFhZmY2ZWZkMzIwYzU="
  expiration: 86400000
  refresh-expiration: 604800000

# Application-specific settings.
app:
  verification-code:
    expiration: 300000
  # User activity settings.
  activity:
    resource:
      add: 1
      delete: -1
      like: 1
      unlike: -1
      view: 1
    interaction:
      add: 1
      delete: 1
      like: 1
      unlike: -1

