# Application configuration demo file for OpenCourse.
# This file is a template and should be copied to application.yml for local use.

# Spring Boot configuration.
spring:
  # Application Information.
  application:
    name: "OpenCourse"
  # SQL settings.
  sql:
    init:
      mode: "never"
  # Database settings.
  datasource:
    url: "jdbc:mysql://mysql:3306/opencourse_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true"
    username: YOUR_USERNAME_HERE      # Change to your MySQL username
    password: YOUR_PASSWORD_HERE      # Change to your MySQL password
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  # JPA/Hibernate settings.
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        # Character encoding settings.
        connection:
          characterEncoding: "utf8"
          useUnicode: true
    open-in-view: false
  # Redis settings.
  data:
    redis:
      host: "redis"
      port: 6379
      password: YOUR_REDIS_PASSWORD   # Change to your Redis password
      timeout: "2000ms"
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: "-1ms"
  # Email settings.
  mail:
    host: SMTP.EXAMPLE.COM            # Change to your SMTP server
    port: 587                         # Change to your SMTP server port
    username: YOUR_EMAIL@EXAMPLE.COM  # Change to your email address
    password: YOUR_EMAIL_PASSWORD     # Change to your email authorization password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  # File upload settings.
  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "100MB"
      enabled: true
  # Jackson JSON settings.
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
    serialization:
      write-dates-as-timestamps: false
  # Security settings.
  security:
    user:
      name: YOUR_ADMIN_USERNAME       # Change to your admin username
      password: YOUR_ADMIN_PASSWORD   # Change to your admin password

# Server settings.
server:
  port: 8080

# Logging settings.
logging:
  level:
    org.opencourse: "INFO"
    root: "WARN"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "logs/opencourse.log"

# MinIO settings.
minio:
  endpoint: "http://minio:9000"       # Change to your MinIO server address
  access-key: YOUR_MINIO_ACCESS_KEY   # Change to your MinIO Access Key
  secret-key: YOUR_MINIO_SECRET_KEY   # Change to your MinIO Secret Key
  bucket-name: "opencourse-resource-files"

# JWT settings.
jwt:
  secret: YOUR_JWT_SECRET_KEY_HERE    # Change to your JWT secret key
  expiration: 86400000
  refresh-expiration: 604800000

# Application-specific settings.
app:
  # User activity settings.
  activity:
    resource:
      add: 1
      delete: -1
      like: 1
      unlike: -1
      view: 1
    interaction:
      add: 1
      delete: 1
      like: 1
      unlike: -1

